# Generated by Django 3.2.12 on 2022-04-02 16:43
from django.core.exceptions import ObjectDoesNotExist
from django.db import migrations

INSTRUCTORS = [

    {
        'first_name': 'Leonard',
        'last_name': 'Buckland',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Megan',
        'last_name': 'Vance',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Blake',
        'last_name': 'Ferguson',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Stephanie',
        'last_name': 'Carr',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Jack',
        'last_name': 'Hill',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Zoe',
        'last_name': 'Sanderson',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Jasmine',
        'last_name': 'Gray',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Amy',
        'last_name': 'Scott',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Bella',
        'last_name': 'Bailey',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Jennifer',
        'last_name': 'Knox',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Anthony',
        'last_name': 'Underwood',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Isaac',
        'last_name': 'Reid',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Michelle',
        'last_name': 'Blake',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Lily',
        'last_name': 'Lewis',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Lauren',
        'last_name': 'Walker',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Gabrielle',
        'last_name': 'Lyman',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Anthony',
        'last_name': 'Peake',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Carol',
        'last_name': 'Scott',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Nicholas',
        'last_name': 'Skinner',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Ella',
        'last_name': 'Manning',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Dominic',
        'last_name': 'Sanderson',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Colin',
        'last_name': 'Dowd',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Theresa',
        'last_name': 'Edmunds',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Michelle',
        'last_name': 'Parsons',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Christopher',
        'last_name': 'Greene',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Mary',
        'last_name': 'Clark',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Kimberly',
        'last_name': 'Berry',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Yvonne',
        'last_name': 'Cameron',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Christian',
        'last_name': 'Skinner',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Lillian',
        'last_name': 'Poole',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Caroline',
        'last_name': 'Alsop',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Nicholas',
        'last_name': 'Underwood',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Rachel',
        'last_name': 'Mackay',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Sebastian',
        'last_name': 'Gibson',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Carol',
        'last_name': 'Paige',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Simon',
        'last_name': 'Buckland',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Faith',
        'last_name': 'Tucker',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Anna',
        'last_name': 'Vaughan',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Robert',
        'last_name': 'Lewis',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Abigail',
        'last_name': 'Paterson',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Victor',
        'last_name': 'Poole',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Julian',
        'last_name': 'Turner',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Leah',
        'last_name': 'Marshall',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Boris',
        'last_name': 'Knox',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Lillian',
        'last_name': 'Bell',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Austin',
        'last_name': 'McLean',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Stewart',
        'last_name': 'Tucker',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Una',
        'last_name': 'Nolan',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Claire',
        'last_name': 'Wright',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Madeleine',
        'last_name': 'Metcalfe',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Carol',
        'last_name': 'Hodges',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Bella',
        'last_name': 'Sharp',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Mary',
        'last_name': 'Glover',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Joshua',
        'last_name': 'Langdon',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Sophie',
        'last_name': 'Hamilton',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Felicity',
        'last_name': 'Welch',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Ella',
        'last_name': 'May',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Katherine',
        'last_name': 'Greene',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Blake',
        'last_name': 'Wallace',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Nicholas',
        'last_name': 'Sanderson',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Elizabeth',
        'last_name': 'Langdon',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Megan',
        'last_name': 'Pullman',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Joe',
        'last_name': 'Morrison',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Ella',
        'last_name': 'Lyman',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Sophie',
        'last_name': 'Hemmings',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Maria',
        'last_name': 'Carr',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Sean',
        'last_name': 'Morgan',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Jack',
        'last_name': 'Hudson',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Vanessa',
        'last_name': 'Watson',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Grace',
        'last_name': 'Dyer',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Natalie',
        'last_name': 'Wright',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Felicity',
        'last_name': 'Davies',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Yvonne',
        'last_name': 'Manning',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Phil',
        'last_name': 'North',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Lily',
        'last_name': 'Rutherford',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Chloe',
        'last_name': 'Hunter',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Bella',
        'last_name': 'Black',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Ruth',
        'last_name': 'Berry',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Stewart',
        'last_name': 'Lee',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Bella',
        'last_name': 'Peters',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Lisa',
        'last_name': 'Wallace',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Oliver',
        'last_name': 'Hudson',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Sarah',
        'last_name': 'Manning',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Richard',
        'last_name': 'Bond',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Cameron',
        'last_name': 'Metcalfe',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Penelope',
        'last_name': 'Clark',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Joshua',
        'last_name': 'Kerr',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Una',
        'last_name': 'Roberts',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Austin',
        'last_name': 'Newman',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Neil',
        'last_name': 'King',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Rachel',
        'last_name': 'Sutherland',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Dylan',
        'last_name': 'Nash',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Edward',
        'last_name': 'Davidson',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Claire',
        'last_name': 'Paige',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'John',
        'last_name': 'Bell',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Wanda',
        'last_name': 'Ross',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Max',
        'last_name': 'Howard',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Tracey',
        'last_name': 'Walker',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Una',
        'last_name': 'Mackay',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Lillian',
        'last_name': 'MacLeod',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Lillian',
        'last_name': 'Black',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Wendy',
        'last_name': 'MacDonald',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Olivia',
        'last_name': 'Stewart',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Carol',
        'last_name': 'Gray',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Victoria',
        'last_name': 'Brown',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Victor',
        'last_name': 'Lee',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Kylie',
        'last_name': 'Clarkson',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Vanessa',
        'last_name': 'Dickens',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Boris',
        'last_name': 'Hill',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Steven',
        'last_name': 'Springer',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Olivia',
        'last_name': 'Dickens',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Jonathan',
        'last_name': 'Lewis',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Jane',
        'last_name': 'Lyman',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'John',
        'last_name': 'Piper',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Colin',
        'last_name': 'Davidson',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Gordon',
        'last_name': 'Lawrence',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Neil',
        'last_name': 'Morrison',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Michael',
        'last_name': 'Peake',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Virginia',
        'last_name': 'Powell',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Julia',
        'last_name': 'Oliver',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Andrea',
        'last_name': 'Jackson',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Julia',
        'last_name': 'Ross',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Chloe',
        'last_name': 'Watson',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Emily',
        'last_name': 'Baker',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Colin',
        'last_name': 'Howard',
        'diambiguator': 'Testing',
    },

]


def add_instructor_data(apps, schema_editor):
    instructor_class = apps.get_model('courseinfo', 'Instructor')
    for instructor in INSTRUCTORS:
        try:
            duplicate_object = instructor_class.objects.get
            print('Duplicate instructor entry not added to instructor table:', instructor['first_name'], instructor['last_name'])
        except ObjectDoesNotExist:
            instructor_object = instructor_class.objects.create(
                first_name=instructor['first_name'],
                last_name=instructor['last_name'],
                diambiguator=instructor['diambiguator']
            )


def remove_instructor_data(apps, schema_editor):
    instructor_class = apps.get_model('courseinfo', 'Instructor')
    for instructor in INSTRUCTORS:
        instructor_object = instructor_class.objects.get
        instructor_object.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('courseinfo', '0003_auto_20220220_1910'),
    ]

    operations = [
        migrations.RunPython(
            add_instructor_data,
            remove_instructor_data
        )
    ]
