# Generated by Django 3.2.12 on 2022-04-02 17:28
from django.core.exceptions import ObjectDoesNotExist
from django.db import migrations

STUDENTS = [

    {
        'first_name': 'Elizabeth',
        'last_name': 'Wilson',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Victor',
        'last_name': 'Lewis',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Christopher',
        'last_name': 'Paterson',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Nicola',
        'last_name': 'Powell',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Ava',
        'last_name': 'White',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Fiona',
        'last_name': 'Bower',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Owen',
        'last_name': 'Reid',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Lily',
        'last_name': 'Miller',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Deirdre',
        'last_name': 'Gill',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Neil',
        'last_name': 'Marshall',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Emily',
        'last_name': 'Sanderson',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Jessica',
        'last_name': 'King',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Adrian',
        'last_name': 'Ogden',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Gabrielle',
        'last_name': 'Lee',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Joshua',
        'last_name': 'Abraham',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Brian',
        'last_name': 'Hill',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Bernadette',
        'last_name': 'Buckland',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Theresa',
        'last_name': 'Thomson',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Ella',
        'last_name': 'Burgess',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Donna',
        'last_name': 'James',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Audrey',
        'last_name': 'Hudson',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Charles',
        'last_name': 'Newman',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Adrian',
        'last_name': 'Black',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Lucas',
        'last_name': 'Wright',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Dorothy',
        'last_name': 'McLean',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Stephen',
        'last_name': 'Glover',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Gabrielle',
        'last_name': 'Poole',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Owen',
        'last_name': 'Edmunds',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Amelia',
        'last_name': 'Bower',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Ava',
        'last_name': 'Graham',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Adam',
        'last_name': 'Taylor',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Lily',
        'last_name': 'Ross',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Joseph',
        'last_name': 'Skinner',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Grace',
        'last_name': 'Greene',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Ryan',
        'last_name': 'Parr',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Peter',
        'last_name': 'Russell',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'William',
        'last_name': 'Mills',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Lucas',
        'last_name': 'Sharp',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Chloe',
        'last_name': 'Anderson',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Lisa',
        'last_name': 'Bond',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Boris',
        'last_name': 'Paterson',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Sam',
        'last_name': 'Wilkins',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Max',
        'last_name': 'Lyman',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Una',
        'last_name': 'Pullman',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Austin',
        'last_name': 'Wilkins',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Lucas',
        'last_name': 'Powell',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Neil',
        'last_name': 'Grant',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Maria',
        'last_name': 'Piper',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Andrea',
        'last_name': 'Walsh',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Anne',
        'last_name': 'Clark',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Tim',
        'last_name': 'Nolan',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Victor',
        'last_name': 'Welch',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Alan',
        'last_name': 'Davidson',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Charles',
        'last_name': 'Churchill',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Jessica',
        'last_name': 'Duncan',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Lucas',
        'last_name': 'Martin',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Maria',
        'last_name': 'Arnold',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Sophie',
        'last_name': 'Clark',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Jacob',
        'last_name': 'Bailey',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Harry',
        'last_name': 'Churchill',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Karen',
        'last_name': 'Lyman',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Trevor',
        'last_name': 'Hunter',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Stephen',
        'last_name': 'Lee',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Vanessa',
        'last_name': 'Underwood',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Richard',
        'last_name': 'Kelly',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Amelia',
        'last_name': 'Campbell',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Zoe',
        'last_name': 'McLean',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Sam',
        'last_name': 'Forsyth',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Phil',
        'last_name': 'Wright',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Maria',
        'last_name': 'Hudson',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Diana',
        'last_name': 'Mackay',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Stewart',
        'last_name': 'Ellison',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Sue',
        'last_name': 'Edmunds',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Karen',
        'last_name': 'Ogden',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Carol',
        'last_name': 'Martin',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Oliver',
        'last_name': 'Wilkins',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Adam',
        'last_name': 'Bower',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Katherine',
        'last_name': 'Clarkson',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Carol',
        'last_name': 'Turner',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Ian',
        'last_name': 'James',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Una',
        'last_name': 'McLean',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Heather',
        'last_name': 'Clark',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Liam',
        'last_name': 'Ellison',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Madeleine',
        'last_name': 'Gill',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Warren',
        'last_name': 'Berry',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Yvonne',
        'last_name': 'Lyman',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Claire',
        'last_name': 'Abraham',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Andrea',
        'last_name': 'Hemmings',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Claire',
        'last_name': 'Clarkson',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Max',
        'last_name': 'Mackenzie',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Luke',
        'last_name': 'Ince',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Samantha',
        'last_name': 'Tucker',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'James',
        'last_name': 'Lewis',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Wendy',
        'last_name': 'Cornish',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Evan',
        'last_name': 'Hamilton',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Caroline',
        'last_name': 'Lee',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Stephanie',
        'last_name': 'Smith',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Lily',
        'last_name': 'Jones',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Melanie',
        'last_name': 'Peake',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Richard',
        'last_name': 'Smith',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Neil',
        'last_name': 'Randall',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'John',
        'last_name': 'Quinn',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Emma',
        'last_name': 'Bell',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Stephanie',
        'last_name': 'Forsyth',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Claire',
        'last_name': 'Young',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Felicity',
        'last_name': 'Avery',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Robert',
        'last_name': 'Glover',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Paul',
        'last_name': 'Tucker',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Abigail',
        'last_name': 'Morrison',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Carl',
        'last_name': 'Ross',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Jack',
        'last_name': 'Parr',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Owen',
        'last_name': 'Ogden',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Grace',
        'last_name': 'Ball',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Felicity',
        'last_name': 'Hill',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Dylan',
        'last_name': 'Fisher',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Angela',
        'last_name': 'Black',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Carolyn',
        'last_name': 'Murray',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Michelle',
        'last_name': 'Morrison',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Penelope',
        'last_name': 'Glover',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Frank',
        'last_name': 'Newman',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Penelope',
        'last_name': 'Blake',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Theresa',
        'last_name': 'Russell',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Trevor',
        'last_name': 'Cameron',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Stephen',
        'last_name': 'Cornish',
        'diambiguator': 'Testing',
    },
    {
        'first_name': 'Anthony',
        'last_name': 'Parr',
        'diambiguator': 'Testing',
    },

]


def add_student_data(apps, schema_editor):
    student_class = apps.get_model('courseinfo', 'Student')
    for student in STUDENTS:
        try:
            duplicate_object = student_class.objects.get
            print('Duplicate student entry not added to student table:', student['first_name'], student['last_name'])
        except ObjectDoesNotExist:
            student_object = student_class.objects.create(
                first_name=student['first_name'],
                last_name=student['last_name'],
                diambiguator=student['diambiguator']
            )


def remove_student_data(apps, schema_editor):
    student_class = apps.get_model('courseinfo', 'Student')
    for student in STUDENTS:
        student_object = student_class.objects.get
        student_object.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('courseinfo', '0004_load_instructor_test_data'),
    ]

    operations = [
        migrations.RunPython(
            add_student_data,
            remove_student_data
        )
    ]
